library(data.table)
library(dplyr)
library(here)
DT <- `[`


source(here("ensvssize", "specs.R"))
loctargets <- enscomb_specs$loctargets
locs <- unique(substr(loctargets, 0, 2))
targs <- unique(substr(loctargets, 3, 100))

set.seed(36)
rdseeds <- expand.grid(location = locs,
                       target_type = targs,
                       kval = enscomb_specs$ks)
rdseeds$seed <- sample.int(10000, size = nrow(rdseeds))
data.table::fwrite(rdseeds, here("enscomb-data", "rdseeds.csv"))

source(here("R", "utils-enscomb.R"))
source(here("ensvssize", "suggested-ens.R"))
source(here("ensvssize", "filter-ens.R"))
source(here("ensvssize", "make-ens.R"))


###from here on, we have to score the ensembles. Since we're running computation-
#intensive pairwise comparisons, I'm running this part on a remote server and not
#locally. Since package arrow doesn't work on that server, I first have to change
#files to .csv format, download scores (after running code on remote server) in
#.csv format, and then change to .parquet.

#changing files generated by make-ens to .csv for server
#source(here("ensvssize", "helper", "change-to-csv.R"))

#running scoring code (on remote server)
#source(here("ensvssize", "save-ensemble.R"))

#download resulting files from server, change to .parquet
#source(here("ensvssize", "helper", "change-to-parquet.R"))
