---
title: "Combination"
author: "Rike"
date: "2023-06-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, message=FALSE}
library(here)
library(data.table)
library(dplyr)
library(ggplot2)
DT <- `[`

nfcsts <- 50
plength <- 10
model_avail <- 0.7

theme_masterthesis <- function() {
  theme_minimal() %+replace%
    theme(axis.line = element_line(colour = "grey80"),
          axis.ticks = element_line(colour = "grey80"),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position = "bottom")
}

fcdat <- fread(here("data", "forecasts.csv"))

comdat <- fcdat |>
  filter(location %in% c("PL", "DE")) |>
  mutate(forecast_date =
           lubridate::round_date(forecast_date,
                                 unit = "week",
                                 week_start = getOption("lubridate.week.start", 6)) #round down to Saturday
  ) |>
  filter(!model == "EuroCOVIDhub-ensemble") |>
  filter(forecast_date >= as.Date("2021-03-20")) |>
  filter(forecast_date <= as.Date("2023-03-11"))  |>
  mutate(forecast_date = as.IDate(forecast_date)) 

fc_dates <- seq.Date(as.Date(min(comdat$forecast_date)),
                     as.Date(max(comdat$forecast_date)), 
                     by = 7)
splitter <- c(1, rep(10, 10)) |> cumsum()

#list for plots (overlapping dates to avoid gaps)
period_cat_plots <- lapply(1:10, function(i) 
  c(fc_dates[splitter[i]], 
    fc_dates[(splitter[i+1])]))

#list with endpoints as correct
period_cat <- lapply(period_cat_plots,
                     function(dat) c(dat[1], dat[2]-7))

#data.table for joining with hub_date
period_cat_dt <- lapply(seq_along(period_cat), 
                        function(k) data.table(forecast_date = 
                                                 seq.Date(period_cat[[k]][1], 
                                                          period_cat[[k]][2], by = 7),
                                               period_cat = k)) |>
  rbindlist() |>
  mutate(period_cat = factor(period_cat),
         forecast_date = as.IDate(forecast_date))




comdat <- comdat |>
  left_join(period_cat_dt, by = "forecast_date")
```

All plots in this document are based on the total available model set at each time point, including the constant baseline, but \textit{not} the Hub ensemble.

```{r, echo = FALSE}
plot_model_availability <- function(data,
                                    saveplot = FALSE,
                                    path = (here("plots", 
                                                 "availability.pdf")),
                                    height = 12, 
                                    width = 8,
                                    indiv = TRUE,
                                    main = NULL,
                                    xlab = NULL,
                                    ylab = NULL,
                                    palette = "Set2"){
  
  
  plot_model_avail_total <- data |>
      dplyr::group_by(forecast_date, location, target_type) |>
      dplyr::summarise(nmods = length(unique(model))-2) |> #subtract 2 bc of baseline, ensemble
      dplyr::ungroup() |>
      ggplot2::ggplot(
        aes(x = forecast_date, y = nmods,
            group = location, 
            color = location)) +
      ggplot2::geom_line(lwd = 1.1) + 
      #ggplot2::scale_color_discrete(name ="", 
      #                        breaks = c("PL", "GB", "FR", "DE", "CZ"),
      #                        labels=c("Poland","United Kingdom","France",
      #                                 "Germany", "Czech R.")) +
      ggplot2::labs(title = main) +
      ggplot2::facet_grid(~ target_type) +
      ggplot2::scale_color_brewer(palette = palette,
                                  name = "",
                                breaks = c("PL", "GB", "FR", "DE", "CZ"),
                                  labels=c("Poland","United Kingdom","France",
                                  "Germany", "Czech Republic")) +  
      ggplot2::scale_x_date(date_breaks = "1 month",
                           date_labels = "%b %y",
                            expand = c(0,0)) +
      ggplot2::ylim(2, 17)+
      theme_masterthesis() %+replace%
      ggplot2::theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
      ggplot2::xlab(xlab) +
      ggplot2::ylab(ylab)  
  
  print(plot_model_avail_total)
}
```
```{r, warning = FALSE, message = FALSE, echo = FALSE}
plot_model_availability(comdat)
```




## Direct recombination

```{r, echo = FALSE, warning=FALSE, fig.width=10,fig.height=5.5 }
comb1 <- comdat |>
  select(model, forecast_date, target_type, location) |>
  distinct() |>
  DT(,  n := .N, by = c("forecast_date", "target_type", "location")) |>
  select(forecast_date, target_type, location, n) |>
  distinct() |>
  mutate("k=4" = choose(n, 4),
         "k=5" = choose(n, 5),
         "k=6" = choose(n, 6),
         "k=7" = choose(n, 7),
         "k=8" = choose(n, 8),
         "k=10" = choose(n, 10)) |>
  melt(id.vars = c("forecast_date", "target_type", "location", "n"),
       variable.name = "k", value.name = "cvg")|>
  mutate(cvg = cut(cvg, breaks = c(-0.1,30,50,700000),
                   labels = c("<30", ">30", ">50")))


ggplot(aes(x = forecast_date, y = k, fill = cvg), data = comb1) +
  geom_tile() +
  scale_fill_brewer() +
  #scale_fill_viridis_d(option = "inferno") +
  facet_grid(location~target_type) +
  labs(fill = "available ensembles") +
  ylab("k (number of models)") +
  xlab("period") +
  theme_masterthesis()
```


## Constant ensembles, by period
### Individual model avail >= 0.7
```{r, echo = FALSE, warning=FALSE, fig.width=10,fig.height=5.5}
comb2 <- comdat |>
  #filter(period_cat == pc) |>
  select(model, forecast_date, period_cat, location, target_type) |>
  distinct()|>
  DT(,  n := .N, by = c("model", "period_cat", "location", "target_type")) |>
  filter(n >= 0.7 * plength) |>
  select(period_cat, model, location, target_type) |>
  distinct() |>
  DT(,  n := .N, by = c("period_cat", "location", "target_type")) |>
  select(period_cat, target_type, location, n) |>
  distinct() |>
  mutate("k=4" = choose(n, 4),
         "k=5" = choose(n, 5),
         "k=6" = choose(n, 6),
         "k=7" = choose(n, 7),
         "k=8" = choose(n, 8),
         "k=10" = choose(n, 10)) |>
  melt(id.vars = c("period_cat", "target_type", "location", "n"),
       variable.name = "k", value.name = "cvg") |>
  mutate(cvg = cut(cvg, breaks = c(-0.1,30,50,50000),
                   labels = c("<30", ">30", ">50")))


ggplot(aes(x = period_cat, y = k, fill = cvg), data = comb2) +
  geom_tile() +
  scale_fill_brewer() +
  #scale_fill_viridis_d(option = "inferno") +
  facet_grid(location~target_type) +
  labs(fill = "available ensembles") +
  ylab("k (number of models)") +
  xlab("period") +
  theme_masterthesis()
```


### Individual model avail >= 0.7
```{r, echo = FALSE, warning=FALSE, fig.width=10,fig.height=5.5}
comb2 <- comdat |>
  #filter(period_cat == pc) |>
  select(model, forecast_date, period_cat, location, target_type) |>
  distinct()|>
  DT(,  n := .N, by = c("model", "period_cat", "location", "target_type")) |>
  filter(n >= 0.7 * plength) |>
  select(period_cat, model, location, target_type) |>
  distinct() |>
  DT(,  n := .N, by = c("period_cat", "location", "target_type")) |>
  select(period_cat, target_type, location, n) |>
  distinct() |>
  mutate("k=4" = choose(n, 4),
         "k=5" = choose(n, 5),
         "k=6" = choose(n, 6),
         "k=7" = choose(n, 7),
         "k=8" = choose(n, 8),
         "k=10" = choose(n, 10)) |>
  melt(id.vars = c("period_cat", "target_type", "location", "n"),
       variable.name = "k", value.name = "cvg") |>
  mutate(cvg = cut(cvg, breaks = c(-0.1,30,50,50000),
                   labels = c("<30", ">30", ">50")))


ggplot(aes(x = period_cat, y = k, fill = cvg), data = comb2) +
  geom_tile() +
  scale_fill_brewer() +
  #scale_fill_viridis_d(option = "inferno") +
  facet_grid(location~target_type) +
  labs(fill = "available ensembles") +
  ylab("k (number of models)") +
  xlab("period") +
  theme_masterthesis()
```

### Individual model avail >= 0.9
```{r, echo = FALSE, warning=FALSE, fig.width=10,fig.height=5.5}
comb2 <- comdat |>
  #filter(period_cat == pc) |>
  select(model, forecast_date, period_cat, location, target_type) |>
  distinct()|>
  DT(,  n := .N, by = c("model", "period_cat", "location", "target_type")) |>
  filter(n >= 0.9 * plength) |>
  select(period_cat, model, location, target_type) |>
  distinct() |>
  DT(,  n := .N, by = c("period_cat", "location", "target_type")) |>
  select(period_cat, target_type, location, n) |>
  distinct() |>
  mutate("k=4" = choose(n, 4),
         "k=5" = choose(n, 5),
         "k=6" = choose(n, 6),
         "k=7" = choose(n, 7),
         "k=8" = choose(n, 8),
         "k=10" = choose(n, 10)) |>
  melt(id.vars = c("period_cat", "target_type", "location", "n"),
       variable.name = "k", value.name = "cvg") |>
  mutate(cvg = cut(cvg, breaks = c(-0.1,30,50,50000),
                   labels = c("<30", ">30", ">50")))


ggplot(aes(x = period_cat, y = k, fill = cvg), data = comb2) +
  geom_tile() +
  scale_fill_brewer() +
  #scale_fill_viridis_d(option = "inferno") +
  facet_grid(location~target_type) +
  labs(fill = "available ensembles") +
  ylab("k (number of models)") +
  xlab("period") +
  theme_masterthesis()
```
