library(here)
library(data.table)

source(here("scripts", "00_download-data", "get-population.R"))
source(here("scripts", "00_download-data", "get-truth.R"))
source(here("scripts", "00_download-data", "get-data.R"))
source(here("scripts", "00_download-data", "get-anomalies.R"))
source(here("scripts", "00_download-data", "get-metadata.R"))
source(here("scripts", "00_download-data", "get-classification.R"))
source(here("scripts", "00_download-data", "make-period-cat.R"))
